name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
    - name: Test
      run: xcodebuild clean test -scheme CSNA -destination platform=iOS\ Simulator,OS=14.2,name=iPhone\ 11
    - name: Analyze
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Docs
      run: echo docs
