name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
    
env:
  XCODE_SCHEME: 'CSNA'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Clean
      run: xcodebuild clean -scheme ${{ XCODE_SCHEME }}
    - name: Build
      run: xcodebuild build -scheme ${{ XCODE_SCHEME }}
    - name: Test
      run: xcodebuild test -scheme ${{ XCODE_SCHEME }}
    - name: Analyze
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Docs
      run: echo docs
